development:
  adapter: postgresql
  encoding: unicode
  database: game_of_thrones_development
  pool: 5
  username: stark
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: game_of_thrones_test
  pool: 5
  username: stark
  password: